version: "3"

networks:
  lecture22:
    external: false

volumes:
  keycloak:
    driver: local
  mongo:
    driver: local

services:
  keycloak:
    image: keycloak18
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=keycloak
      # NOTE: this is only for demonstration purposes
      # ordinarily, you should NOT embed passwords in files
      - KEYCLOAK_PASSWORD=keycl0ak
    restart: always
    networks:
      - lecture22
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    ports:
      - "127.0.0.1:8081:8080"
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    networks:
      - lecture22
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
